!!net.sourceforge.marathon.objectmap.ObjectMapConfiguration
containerNamingProperties:
-   className: java.awt.Window
    propertyLists: []
-   className: javax.swing.JInternalFrame
    propertyLists: []
-   className: javax.swing.JWindow
    propertyLists: []
-   className: javafx.stage.Stage
    propertyLists:
    -   priority: 100
        properties: [title]
containerRecognitionProperties:
-   className: java.awt.Window
    propertyLists: []
-   className: javax.swing.JInternalFrame
    propertyLists: []
-   className: javax.swing.JWindow
    propertyLists: []
-   className: javafx.stage.Stage
    propertyLists:
    -   priority: 100
        properties: [title]
generalProperties: [labeledBy, toolTipText, name, labelText, precedingLabel, cText,
    iconFile, position, size, accelerator, enabled, toolTipText, fieldName, layoutData.gridx,
    layoutData.gridy, layoutData.x, layoutData.y, accessibleContext.accessibleName,
    tagName, instanceOf, component.class.name]
namingProperties:
-   className: java.awt.Component
    propertyLists: []
-   className: javax.swing.JLabel
    propertyLists: []
-   className: javafx.scene.Node
    propertyLists:
    -   priority: 100
        properties: [labeledBy]
    -   priority: 90
        properties: [id]
    -   priority: 80
        properties: [accessibleName]
recognitionProperties:
-   className: java.awt.Component
    propertyLists: []
-   className: javafx.scene.Node
    propertyLists:
    -   priority: 100
        properties: [tagName, Id]
    -   priority: 90
        properties: [tagName, text]
